pring.application.name=api_helpdesk_sofwate

# Core
spring.profiles.active=devh2

#base end-points config
api-endpoint = api/v1

#docker
spring:
  docker:
    compose:
      service-connection:
        enabled: false